"""empty message

Revision ID: 19eef85559c6
Revises: 6b4f90e7f9c6
Create Date: 2020-09-11 21:33:03.895934

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19eef85559c6'
down_revision = '6b4f90e7f9c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor', 'pharmacy_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('pharmacy_id', mysql.INTEGER(
        display_width=11), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
