"""empty message

Revision ID: 1f3b75e3b93c
Revises: f8fdfcbee7bb
Create Date: 2020-09-05 23:09:47.658369

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f3b75e3b93c'
down_revision = 'f8fdfcbee7bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
