"""empty message

Revision ID: 34789c6c2e01
Revises: 5b867877cd6d
Create Date: 2020-08-31 17:14:39.625137

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34789c6c2e01'
down_revision = '5b867877cd6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
