"""empty message

Revision ID: 50b8cdae0e1b
Revises: cd19f7fa0b9d
Create Date: 2020-08-29 18:13:47.598141

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50b8cdae0e1b'
down_revision = 'cd19f7fa0b9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('report_ibfk_5', 'report', type_='foreignkey')
    op.drop_column('report', 'history_of_pharmacy_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('history_of_pharmacy_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('report_ibfk_5', 'report', 'history_of_pharmacy', ['history_of_pharmacy_id'], ['id'])
    # ### end Alembic commands ###
