"""empty message

Revision ID: 702b65f77f47
Revises: 34789c6c2e01
Create Date: 2020-08-31 18:22:41.987942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '702b65f77f47'
down_revision = '34789c6c2e01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('email', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'user', 'zone', ['zone_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('doctor', 'email')
    # ### end Alembic commands ###
