"""empty message

Revision ID: 7132ecc51e28
Revises: b794802a3f64
Create Date: 2020-08-30 15:57:47.534455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7132ecc51e28'
down_revision = 'b794802a3f64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('history_of_pharmacy_ibfk_4', 'history_of_pharmacy', type_='foreignkey')
    op.create_foreign_key(None, 'history_of_pharmacy', 'pharmacy', ['pharmacy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'history_of_pharmacy', type_='foreignkey')
    op.create_foreign_key('history_of_pharmacy_ibfk_4', 'history_of_pharmacy', 'report', ['pharmacy_id'], ['pharmacy_id'])
    op.drop_table('notification')
    # ### end Alembic commands ###
