"""empty message

Revision ID: aaf374d23edd
Revises: 7132ecc51e28
Create Date: 2020-08-30 16:09:34.955793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf374d23edd'
down_revision = '7132ecc51e28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('seen', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'seen')
    # ### end Alembic commands ###
