"""empty message

Revision ID: b794802a3f64
Revises: 0680101ced60
Create Date: 2020-08-29 20:18:07.261932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b794802a3f64'
down_revision = '0680101ced60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('history_of_pharmacy_ibfk_2', 'history_of_pharmacy', type_='foreignkey')
    op.create_foreign_key(None, 'history_of_pharmacy', 'report', ['pharmacy_id'], ['pharmacy_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'history_of_pharmacy', type_='foreignkey')
    op.create_foreign_key('history_of_pharmacy_ibfk_2', 'history_of_pharmacy', 'pharmacy', ['pharmacy_id'], ['id'])
    # ### end Alembic commands ###
