"""empty message

Revision ID: cd19f7fa0b9d
Revises: 4bb029164596
Create Date: 2020-08-29 17:33:04.788953

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd19f7fa0b9d'
down_revision = '4bb029164596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('availabilty_of_item', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('availabilty_of_item', sa.Column('comment', mysql.VARCHAR(length=500), nullable=True))
    # ### end Alembic commands ###
